# Generated by Django 3.2.13 on 2022-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='imdb',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='IMDb Linki'),
        ),
        migrations.AlterField(
            model_name='content',
            name='yazi',
            field=models.TextField(max_length=10000, verbose_name='İçerik Yazısı'),
        ),
    ]
