# Generated by Django 3.2.13 on 2022-11-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20221023_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isim',
            field=models.CharField(max_length=100, null=True, verbose_name='Yazı Sahibi'),
        ),
        migrations.AddField(
            model_name='content',
            name='tarih',
            field=models.DateTimeField(null=True, verbose_name='Yazı Tarihi'),
        ),
    ]
