# Generated by Django 3.2.13 on 2022-11-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20221101_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tarih',
        ),
    ]
