# Generated by Django 3.2.13 on 2022-11-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_content_tarih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='isim',
        ),
    ]
