# Generated by Django 3.2.13 on 2022-11-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_isim'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tarih',
            field=models.DateField(null=True, verbose_name='Yazı Tarihi'),
        ),
    ]
