# Generated by Django 3.2.13 on 2022-11-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi_sahibi', models.CharField(max_length=100, null=True, verbose_name='Yazı Sahibi')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='tarih',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Yazı Tarihi'),
        ),
        migrations.AlterField(
            model_name='content',
            name='isim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.name', verbose_name='Yazı Sahibi'),
        ),
    ]
