# Generated by Django 3.2.13 on 2022-11-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20221110_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='isim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.name', verbose_name='Yazı Sahibi'),
        ),
        migrations.AlterField(
            model_name='name',
            name='yazi_sahibi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yazı Sahibi'),
        ),
    ]
