# Generated by Django 3.2.13 on 2022-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20221110_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='isim',
            field=models.CharField(max_length=200, null=True, verbose_name='Yazı Sahibi'),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
