# Generated by Django 3.2.13 on 2022-11-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20221110_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='isim',
        ),
    ]
