# Generated by Django 3.2.13 on 2022-11-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_content_isim'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isim',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yazı Sahibi'),
        ),
    ]
