# Generated by Django 3.2.13 on 2022-11-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_content_isim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi_sahibi', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='isim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.name'),
        ),
    ]
